### ISSUE TITLE
patent_client is limited to 3.7

### ISSUE THREAD

**Issue by bbelderbos** [IshanMi/reverse-image-search-patent#5]
Running your app:

```
(venv) √ reverse-image-search-patent (main) $ python --version
Python 3.9.5
(venv) √ reverse-image-search-patent (main) $ python app.py
Traceback (most recent call last):
  File "/Users/bbelderbos/code/PDM/projects/ishan/reverse-image-search-patent/app.py", line 2, in <module>
    from src.patent_fetcher import conduct_search
  File "/Users/bbelderbos/code/PDM/projects/ishan/reverse-image-search-patent/src/patent_fetcher.py", line 2, in <module>
    from patent_client import USApplication
  File "/Users/bbelderbos/code/PDM/projects/ishan/reverse-image-search-patent/venv/lib/python3.9/site-packages/patent_client/__init__.py", line 50, in <module>
    from patent_client.uspto.peds.model import USApplication
  File "/Users/bbelderbos/code/PDM/projects/ishan/reverse-image-search-patent/venv/lib/python3.9/site-packages/patent_client/uspto/peds/model.py", line 206, in <module>
    class Relationship(Model):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/dataclasses.py", line 1013, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/dataclasses.py", line 898, in _process_class
    raise TypeError('cannot inherit frozen dataclass from a '
TypeError: cannot inherit frozen dataclass from a non-frozen one
```

Interestingly:

<img width="1555" alt="image" src="https://user-images.githubusercontent.com/387927/119858337-abf2cf80-bf14-11eb-8763-5c2241c032f2.png">

Seems 3.7 max!
https://pypi.org/project/patent-client/

**Comment by bbelderbos** [comment]
@IshanMi ok I got it running now after installing some more libs so I updated the requirements: https://github.com/IshanMi/reverse-image-search-patent/commit/71815ab7a05870bf76c8a83b437f141335d0dda1
